source 'https://rubygems.org'
gem 'activesupport', '~> 4.1.1'
gem 'daemons'
gem 'fog'
gem 'haml'
gem 'i18n'
gem 'net-ssh'
gem 'net-sftp'
gem 'pony'
gem 'rake'
gem 'redis-objects'
gem 'rest-client'
gem 'sidekiq', '~> 3.0.0'
gem 'sidekiq-middleware'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-synchrony'
gem 'sys-filesystem'
gem 'unf'
gem 'uuid'
gem 'uuidtools'

case RUBY_ENGINE
when 'ruby'
  gem 'thin'
when 'rbx'
  gem 'puma'
  gem 'rubysl'
when 'jruby'
  gem 'puma'
end
