source 'http://rubygems.org'
gem 'activesupport', '~> 3.2'
gem 'aws'
gem 'daemons'
gem 'i18n'
gem 'net-ssh'
gem 'net-sftp'
#gem 'redis', '~> 3.0.1'
gem 'resque'
gem 'resque-lock-timeout'
gem 'resque-pool'
gem 'rest-client'
gem 'uuid'
