source 'https://rubygems.org'
gem 'activesupport', '~> 3.2.12'
gem 'daemons'
gem 'fog'
gem 'haml'
gem 'i18n'
gem 'net-ssh'
gem 'net-sftp'
gem 'pony'
gem 'redis-objects'
gem 'rest-client'
gem 'sidekiq'
gem 'sidekiq-unique-jobs'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-synchrony'
gem 'thin'
gem 'uuid'
