#!/bin/sh

WORKER="$(basename $0)"
CFGFILE="$(dirname $0)/${WORKER}.yml"
PIDFILE="$(dirname $0)/tmp/pids/${WORKER}.pid"

pool_getcount()
{
  if [ -f "${CFGFILE}" ]; then
    COUNT="$(cat ${CFGFILE})"
    COUNT="${COUNT##* }"
  fi
}

pool_setcount()
{
  if [ "$1" -eq "$1" 2> /dev/null ]; then
    echo "$(basename $0): $1" > "${CFGFILE}"
  fi
}

pool_getpid()
{
  if [ -f "${PIDFILE}" ]; then
    PID="$(cat $PIDFILE)"
    if [ ! "$(ps -A | grep ${PID} 2>/dev/null)" ]; then
      echo "$PID not running, cleaning up."
      rm "${PIDFILE}"
      unset PID
    fi
  else
    unset PID
  fi
}

pool_run()
{
  pool_getpid
  pool_getcount
  if [ ! "${PID}" ]; then
    echo "Starting resque pool."
    resque-pool run
  fi
}

pool_start()
{
  pool_getpid
  pool_getcount
  if [ ! "${PID}" ]; then
    echo "Starting ${WORKER} pool with ${COUNT} workers."
    resque-pool -d -c "${CFGFILE}" -p "${PIDFILE}"
  fi
}

pool_stop()
{
  pool_getpid
  pool_getcount
  if [ "${PID}" ]; then
    echo "Stopping ${WORKER} pool."
    kill -QUIT $PID
    echo "Waiting for workers to finish."
    while [ -f "${PIDFILE}" ]; do
      sleep 2
    done
  fi
}

pool_reload()
{
  pool_getpid
  pool_getcount
  if [ "${PID}" ]; then
    echo "Reloading ${WORKER} pool with ${COUNT} workers."
    kill -HUP $PID
  fi
}

pool_pause()
{
  pool_getpid
  pool_getcount
  if [ "${PID}" ]; then
    echo "Pausing ${WORKER} pool."
    kill -WINCH $PID
  fi
}

pool_status()
{
  pool_getpid
  pool_getcount
  if [ "${PID}" ]; then
    echo "Status: ${WORKER} running with ${COUNT} workers"
  else
    echo "Status: ${WORKER} stopped"
  fi
}

usage()
{
  echo "Usage: $(basename $0) [start|stop|restart|status|reload|pause] [count]"
}

case "$1" in
  start)
    pool_setcount $2
    pool_start
    ;;
  run)
    pool_setcount $2
    pool_run
    ;;
  stop)
    pool_stop
    ;;
  restart)
    pool_setcount $2
    pool_stop
    pool_start
    ;;
  reload)
    pool_setcount $2
    pool_reload
    ;;
  pause)
    pool_pause
    ;;
  status)
    pool_status
    ;;
  *)
    usage
    ;;
esac
